wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.13
anneal_clr_by_factor:
  desc: null
  value: 1.0
backward_iters:
  desc: null
  value: 10
batch_size:
  desc: null
  value: 64
budget:
  desc: null
  value: 0.1
clip_obs:
  desc: null
  value: 20
clip_range:
  desc: null
  value: 0.2
clip_range_cost_vf:
  desc: null
  value: null
clip_range_reward_vf:
  desc: null
  value: null
cn_acs_select_dim:
  desc: null
  value:
  - -1
cn_batch_size:
  desc: null
  value: null
cn_eps:
  desc: null
  value: 1.0e-05
cn_layers:
  desc: null
  value:
  - 2
cn_learning_rate:
  desc: null
  value: 0.05
cn_normalize:
  desc: null
  value: false
cn_obs_select_dim:
  desc: null
  value:
  - 0
  - 1
cn_plot_every:
  desc: null
  value: 5
cn_reg_coeff:
  desc: null
  value: 0.002
cn_target_kl_new_old:
  desc: null
  value: 2.5
cn_target_kl_old_new:
  desc: null
  value: 10
config_file:
  desc: null
  value: null
cost_gae_lambda:
  desc: null
  value: 0.95
cost_gamma:
  desc: null
  value: 0.99
cost_info_str:
  desc: null
  value: cost
cost_vf_coef:
  desc: null
  value: 0.5
cost_vf_layers:
  desc: null
  value:
  - 16
  - 16
debug_mode:
  desc: null
  value: false
derivative_control_coeff:
  desc: null
  value: 0
derivative_cost_ema_alpha:
  desc: null
  value: 0.5
device:
  desc: null
  value: cpu
dont_normalize_cost:
  desc: null
  value: false
dont_normalize_obs:
  desc: null
  value: false
dont_normalize_reward:
  desc: null
  value: false
ent_coef:
  desc: null
  value: 0.005
eval_env_id:
  desc: null
  value: PointCircleTest-v0
eval_every:
  desc: null
  value: 2048
expert_path:
  desc: null
  value: icrl/expert_data/PointCircle
expert_rollouts:
  desc: null
  value: 20
failed_rollouts:
  desc: null
  value: 10
file_to_run:
  desc: null
  value: icrl
forward_timesteps:
  desc: null
  value: 20000
group:
  desc: null
  value: Point-ICRL
integral_control_coeff:
  desc: null
  value: 0.0001
learning_rate:
  desc: null
  value: 0.0006
loading_policy:
  desc: null
  value: false
loading_policy_dir:
  desc: null
  value: run-20230127_122013-1e0talqx
loading_policy_ite:
  desc: null
  value: '20'
max_grad_norm:
  desc: null
  value: 0.5
n_epochs:
  desc: null
  value: 10
n_iters:
  desc: null
  value: 250
n_steps:
  desc: null
  value: 2048
name:
  desc: null
  value: PointCircle-v0_PointCircleTest-v0_clr_0.05_crc_0.002_ctkno_2.5_ec_0.005_ep_PointCircle_ft_20000_psis_True_tk_0.01_wt_1200000_s_23_sid_-1
no_importance_sampling:
  desc: null
  value: false
num_threads:
  desc: null
  value: 23
penalty_initial_value:
  desc: null
  value: 1
penalty_learning_rate:
  desc: null
  value: 0.3
per_step_importance_sampling:
  desc: null
  value: true
pid_delay:
  desc: null
  value: 1
policy_layers:
  desc: null
  value:
  - 16
  - 16
policy_name:
  desc: null
  value: TwoCriticsMlpPolicy
project:
  desc: null
  value: ICRL-FE2
proportional_control_coeff:
  desc: null
  value: 10
proportional_cost_ema_alpha:
  desc: null
  value: 0.5
reset_policy:
  desc: null
  value: false
reward_gae_lambda:
  desc: null
  value: 0.95
reward_gamma:
  desc: null
  value: 0.99
reward_vf_coef:
  desc: null
  value: 0.5
reward_vf_layers:
  desc: null
  value:
  - 16
  - 16
save_dir:
  desc: null
  value: ./icrl/wandb/run-20230130_110254-uysl0q7k/files
save_every:
  desc: null
  value: 1
sde_sample_freq:
  desc: null
  value: -1
seed:
  desc: null
  value: 23
shared_layers:
  desc: null
  value: null
sync_wandb:
  desc: null
  value: false
table_function:
  desc: null
  value: false
target_kl:
  desc: null
  value: 0.01
train_env_id:
  desc: null
  value: PointCircle-v0
train_gail_lambda:
  desc: null
  value: false
update_penalty_after:
  desc: null
  value: 1
use_curiosity_driven_exploration:
  desc: null
  value: false
use_pid:
  desc: null
  value: false
use_sde:
  desc: null
  value: false
verbose:
  desc: null
  value: 2
wandb_sweep:
  desc: null
  value: false
warmup_timesteps:
  desc: null
  value: 1200000
with_failed_data:
  desc: null
  value: false
